props := $(filter-out 35,$(filter-out 34,$(filter-out 33,$(shell seq -w 1 50))))
expensive_props = 33 34 35

prop_prefix = prop_T

targets :=

HIPSPEC_EXPENSIVE_FLAGS = --pvars --size 7

include ../Makefile.common

