
angular.min.js:
	wget http://code.angularjs.org/1.0.5/angular.min.js

angular.js:
	wget http://code.angularjs.org/1.0.5/angular.js

underscore.js:
	wget http://underscorejs.org/underscore.js

underscore-min.js:
	wget http://underscorejs.org/underscore-min.js

all: angular.min.js angular.js underscore.js underscore-min.js

clean:
	rm -f angular.min.js angular.js underscore.js underscore-min.js

.PHONY: all clean
